// <auto-generated />
using System;
using LogStore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogStore.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200815010025_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("LogStore.Domain.Models.Order", b =>
                {
                    b.Property<long>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("LogStore.Domain.Models.OrderItem", b =>
                {
                    b.Property<long>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrderSubItemID")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("LogStore.Domain.Models.OrderSubItem", b =>
                {
                    b.Property<long>("OrderSubItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrderItemID")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProductID")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderSubItemID");

                    b.HasIndex("OrderItemID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderSubItem");
                });

            modelBuilder.Entity("LogStore.Domain.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            Description = "Molho de tomate coberto por três tipo de queijo",
                            Name = "3 Queijos",
                            Value = 50m
                        },
                        new
                        {
                            ProductID = 2L,
                            Description = "Molho de tomate coberto de frango com requeijão",
                            Name = "Frango com Requeijão",
                            Value = 59.99m
                        },
                        new
                        {
                            ProductID = 3L,
                            Description = "Molho de tomate coberto por queijo mussarela",
                            Name = "Mussarela",
                            Value = 42.50m
                        },
                        new
                        {
                            ProductID = 4L,
                            Description = "Molho de tomate coberto por calabresa e cebola",
                            Name = "Calabresa",
                            Value = 42.50m
                        },
                        new
                        {
                            ProductID = 5L,
                            Description = "Molho de tomate coberto por pepperoni",
                            Name = "Pepperoni",
                            Value = 55m
                        },
                        new
                        {
                            ProductID = 6L,
                            Description = "Molho de tomate coberto por mussarela, pressunto, ovo e banco",
                            Name = "Portuguesa ",
                            Value = 45m
                        },
                        new
                        {
                            ProductID = 7L,
                            Description = "Molho de tomate coberto por mussarela, Tomate e ervilha",
                            Name = "Veggie  ",
                            Value = 59.99m
                        });
                });

            modelBuilder.Entity("LogStore.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("LogStore.Domain.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("LogStore.Domain.Models.OrderSubItem", b =>
                {
                    b.HasOne("LogStore.Domain.Models.OrderItem", "OrderItem")
                        .WithMany("SubItems")
                        .HasForeignKey("OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogStore.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });
#pragma warning restore 612, 618
        }
    }
}
